### ISSUE TITLE
feat: modify header styling with RWD

### ISSUE THREAD

**Issue by Alanwei0502** [godmmt/MERN-app#10]
1. 最左側加一個 logo
2. header 裡面塞一個 navbar：其中包含 about us、course、postCourse
3. login、register、logout 移到最右側，並加上一個 user avatar，點擊進入 profile
4. 手機版時，將 navbar、login、register、logout、avatar合併成 hamburger menu

**Comment by godmmt** [comment]
目前畫面中header右側沒有register，請問是否要加上register ? 

![image](https://github.com/godmmt/MERN-app/assets/105651918/c57f6434-98fb-44d4-b45e-81e76cd22c83)

**Comment by Alanwei0502** [comment]
想改成點擊Login後，會跳出Modal，Modal預設是登入帳密，下方有一個Register按鈕，如果還沒有帳號可以點擊這個按鈕，Modal就改成要填寫註冊的內容。
