### ISSUE TITLE
Refactor: Component files structure

### ISSUE THREAD

**Issue by Alanwei0502** [godmmt/MERN-app#3]
重構組件結構，並使用 .jsx 為副檔名，非組件檔案用 .js 即可，方便區分

- components
   - course
      - index.jsx
   - enroll
      - index.jsx
   - home
   - login

**Comment by godmmt** [comment]
#5 已經上分支了，請檢查一下 @Alanwei0502

**Comment by Alanwei0502** [comment]
Done
