### ISSUE TITLE
Feature: Register add validation for role

### ISSUE THREAD

**Issue by godmmt** [godmmt/MERN-app#40]
### Add validation for the dropdown menu on the registration page.

value改為0 & 1，取代原先直接輸入的student & instructor **-->先不做**

似乎不需要做驗證(?)

**Comment by godmmt** [comment]
感覺下拉式選單在前端就會被擋下了
所以也不需要驗證，對吧？ @Alanwei0502 

![image](https://github.com/godmmt/MERN-app/assets/105651918/1adadd68-224f-4a07-8c4a-9cbd5b885008)

**Comment by Alanwei0502** [comment]
最好後端還是要做驗證，UI雖然可以擋下來，但懂前端的人可以不使用表單，直接在console打api做登入。通常後端是最後防線，一定要擋

**Comment by Alanwei0502** [comment]
但這個紅字應該是後端回傳擋下來的，前端的「是否有選取選項的驗證」可寫可不寫。

**Comment by godmmt** [comment]
> 前端的「是否有選取選項的驗證」可寫可不寫

哈哈哈沒錯
我昨天研究了一下是我後端裝的模組joi，他所回傳的錯誤訊息
笑死

**Comment by Alanwei0502** [comment]
但是按鈕的部分建議可以做一個Loading，就是發出 request 之後，response 還沒回傳的期間都不可以點擊。

這個概念跟「防抖 debounce」、「節流 throttle」有點類似，避免client端瘋狂對server發請求。

你可以想一下這個要怎麼寫。不會沒關係，就發 issue 之後再來改～

備註：防抖節流也是面試常考題之一
