### ISSUE TITLE
Feature: btn-req-loading

### ISSUE THREAD

**Issue by godmmt** [godmmt/MERN-app#46]
_Originally posted by @Alanwei0502 in https://github.com/godmmt/MERN-app/issues/40#issuecomment-1667378276_

> 但是按鈕的部分建議可以做一個Loading，就是發出 request 之後，response 還沒回傳的期間都不可以點擊。
這個概念跟「防抖 debounce」、「節流 throttle」有點類似，避免client端瘋狂對server發請求。
你可以想一下這個要怎麼寫。不會沒關係，就發 issue 之後再來改～
備註：防抖節流也是面試常考題之一

**Comment by Alanwei0502** [comment]
參考：https://css-loaders.com/dots/

**Comment by godmmt** [comment]
> 參考：https://css-loaders.com/dots/

也太酷了吧 😎

**Comment by Alanwei0502** [comment]
> > 參考：https://css-loaders.com/dots/
> 
> 也太酷了吧 😎

可以看telegram的手刻版，順便練習怎麼刻
