### ISSUE TITLE
Contact 頁面的地圖大一點

### ISSUE THREAD

**Issue by Alanwei0502** [godmmt/MERN-app#64]
![截圖 2023-09-08 上午12 42 47](https://github.com/godmmt/MERN-app/assets/63702945/33095718-3655-4ec5-b78e-a337da67c332)

**Comment by godmmt** [comment]
@Alanwei0502  你檢查看看現在地圖尺寸是否可以？OK的話再幫我關閉 issue 😄 謝謝
